### ISSUE TITLE
Can't append records to MS SQL Server Table with Auto Increment ID field

### ISSUE THREAD

**Issue by ben519** [cran/RODBC#1]
I can't seem to append records to a SQL table with an Auto-Increment ID field. I tried using the sqlSave() method with a number of parameter variations but nothing worked.

For more details on this issue see 
http://stackoverflow.com/questions/29833437/rodbc-error-cannot-insert-explicit-value-for-identity-column
http://stackoverflow.com/questions/6353644/how-to-skip-primary-key-in-sqlsave-command
http://r.789695.n4.nabble.com/sqlsave-and-mysql-database-with-autoincremental-column-td3251425.html

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN. Please send the bug to the package authors, see `DESCRIPTION`. Thanks!
